name: starchat
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.9
  - tqdm==4.65.0
  - transformers==4.28.1
  - datasets==2.11.0
  - huggingface_hub==0.13.4
  - accelerate==0.18.0
  - ca-certificates
  - openssl
  - flask
  - gunicorn
  - certifi
  - pylint
  - pip
  - scipy
  - pytorch
  - pytorch-cuda=11.8
  - torchvision
  - torchaudio
  - pip:
    - bitsandbytes
